language: node_js
node_js:
  - "node"
  - "0.12"
  - "0.11"
  - "iojs"
  - "iojs-v1.0.4" 
before_script:
  - sleep 15
  - mongo mongorestify_test --eval 'db.addUser("mongorestify", "mongorestify");'
services:
  - mongodb